apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: client
spec:
  serviceName: client
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: confluentinc/cp-kafka:latest
        command:
        - /bin/sh
        - -c
        - |
          kafka-producer-perf-test \
            --topic ${HOSTNAME}  \
            --record-size 524288 \
            --throughput 64 \
            --producer.config /mnt/kafka.properties \
            --num-records 230400
        resources:
          requests:
            memory: 512Mi # 768Mi
            cpu: 500m # 1000m
---
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  clusterIP: None