apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: client
spec:
  serviceName: client
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: confluentinc/cp-kafka:latest
        resources:
          requests:
            memory: 512Mi # 768Mi
            cpu: 500m # 1000m
---
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  clusterIP: None