apiVersion: v1
kind: Secret
metadata:
  name: spring-boot-application-yaml
type: Opaque
stringData:
  application.yaml: |
    spring:
      kafka:
        properties:
          bootstrap.servers: kafka.gitops-confluent.svc.cluster.local:9071
      cloud:
        stream:
          function:
            definition: produceData;consumeData
          bindings:
            # kafka producer
            produceData-out-0:
              binder: kafka
              destination: gitops-quotes
              producer:
                partition-count: 2
                useNativeEncoding: true
            # kafka consumer
            consumeData-in-0:
              binder: kafka
              destination: gitops-quotes
              group: gitops-boot-app-consumer
          kafka:
            binder:
              consumer-properties:
                key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
                value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
              producer-properties:
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
                value.serializer: org.apache.kafka.common.serialization.StringSerializer
