apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: datagen-topic-consumergroup
  namespace: confluent
spec:
  principal:
    name: devuser
    type: user
  resourcePatterns:
  - name: boot-app-consumer
    patternType: LITERAL
    resourceType: Group
  - name: console-consumer
    patternType: PREFIXED
    resourceType: Group
  - name: prod-quotes
    patternType: LITERAL
    resourceType: Topic
  role: ResourceOwner 
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: datagen-consumergroup
  namespace: confluent
spec:
  principal:
    name: devuser
    type: user
  resourcePatterns:
  - name: boot-app-consumer
    patternType: LITERAL
    resourceType: Group
  role: ResourceOwner

  # console-consumer-61965