apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: datagen
build:
  artifacts:
    - image: docker.io/rohit2b/datagen
      context: datagen
    - image: docker.io/rohit2b/wordcount
      context: wordcount
deploy:
  kubectl:
    manifests:
      - datagen-app-secret.yaml
      - wordcount-app-secret.yaml
      - datagen-app-deployment.yaml
      - wordcount-app-deployment.yaml